server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/videoconf
    username: videoconf
    password: videoconf
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  file:
    name: logs/videoconf.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 500MB
  level:
    com.example.videoconf: DEBUG
    org.springframework.security: WARN
    org.springframework.web: INFO

app:
  keycloak:
    base-url: ${KEYCLOAK_ADMIN_BASE_URL:http://localhost:8181}
    realm: ${KEYCLOAK_ADMIN_REALM_NAME:video-conf}
    master-username: ${KEYCLOAK_MASTER_USERNAME:admin}
    master-password: ${KEYCLOAK_MASTER_PASSWORD:admin}
