[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = GNYv1fI00AuvEP4v7xGtRtFU0GmNOaXte468XgM+v2o=

[Peer]
PublicKey = dKK1sBMin4/+IK8QTtW+RKLc7U0/LOReWPh3qW/MuFw=
AllowedIPs = 10.0.0.2/32
